name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  publish:
      name: Publish
      runs-on: ubuntu-latest
      steps:
        - name: Publish to Wally
            env: 
              WALLY_TOKEN: ${{ secrets.WALLY_AUTH_TOKEN }}
            run: |
              mkdir =p ~/.wally
              printf "[tokens]\n\"https://api.wally.run/\" = \"%s\"" "$WALLY_TOKEN" >> ~/.wally/auth.toml
              wally publish