name: CI

on: push

jobs: 

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main
        uses: actions/checkout@v3

      - name: Run Stylua
        run: stylua lib --check

      - name: Run Selene
        run : selene lib